### ISSUE TITLE
How to add background transparency and blur for vscode

### ISSUE THREAD

**Issue by iafshinafshin** [SolDoesTech/hyprland#13]
How to add background transparency and blur for vscode

**Comment by jjaimealeman** [comment]
> How to add background transparency and blur for vscode

There's this extension https://marketplace.visualstudio.com/items?itemName=s-nlf-fh.glassit

**BUT** requires X-org server, so no. Not compatible with hyprland, as hyprland runs on wayland.

---

_UPDATE:_ as I was searching (as this is actually a sweet idea) I came across this https://aur.archlinux.org/packages/code-translucent

BUT BE WARNED: it has NOT been updated since 2022/09.

---

Further searching reveals that you CAN use an extension to give VS Code a background image https://medium.com/@omobolanlearogundade/how-to-change-the-background-image-in-visual-studio-code-8717f5e4e107

Not really what you want, kinda hacky, but still pretty cool.

**Comment by jojo-firedev** [comment]
I had just added following line to my ~/.config/hypr/hyperland.conf
`windowrulev2 = opacity 0.8 0.8,class:^(Code)$`

If you use this repository for your config, then there is already a config for this in line 121. Just remove the #
https://github.com/SolDoesTech/hyprland/blob/main/hypr/hyprland.conf#L121C1-L121C48

**Comment by jjaimealeman** [comment]
> I had just added following line to my ~/.config/hypr/hyperland.conf 
> `windowrulev2 = opacity 0.8 0.8,class:^(Code)$`
> 

Worked perfectly! 👍
